window.QUIZ_SETS = {
  latihan1: {
    title: "Latihan 1",
    subtitle: "10 soalan • 6 petikan",
    audioFolder: "audio",
    questions: [
      {"id":1,"section":"Petikan 1","track":"02 Track 2.mp3","question":"Mengapakah Radio1FM mengadakan acara bersenam beramai-ramai itu?","options":["Untuk menyambut ulang tahunnya yang ke-10","Untuk mempromosikan Taman Pesisiran kepada orang ramai","Untuk menggalakkan orang ramai mengamalkan aktiviti bersenam","Untuk memperkenalkan deejay-deejay dan artis-artis daripada Radio1FM"],"answer":0,"explanation":"Jawapan yang tepat ialah A."},
      {"id":2,"section":"Petikan 2","track":"03 Track 3.mp3","question":"Apakah yang membuat Azri berasa marah pada pagi itu?","options":["Kucing-kucingnya dilaporkan di akhbar.","Dia membaca berita tentang kucing-kucing yang teraniaya.","Pihak berkuasa tidak mengambil tindakan terhadap pemilik kucing.","Siasatan terhadap pemilik kucing yang tidak bertanggungjawab belum berakhir."],"answer":1,"explanation":"Jawapan yang tepat ialah B."},
      {"id":3,"section":"Petikan 3","track":"04 Track 4.mp3","question":"Apakah yang ingin dicapai melalui Kempen Internet Lebih Baik?","options":["Mengurangkan sebaran berita palsu di Internet.","Para belia dapat menyebarkan berita dalam talian.","Para belia bersikap positif semasa menggunakan Internet.","Menggalakkan para belia menjadi pengguna aktif Internet."],"answer":2,"explanation":"Jawapan yang tepat ialah C."},
      {"id":4,"section":"Petikan 4","track":"05 Track 5.mp3","question":"Apakah itu dimensia?","options":["Proses penuaan yang normal","Penyakit lupa yang dialami oleh manusia","Penyakit yang dialami oleh semua warga tua","Satu penyakit disebabkan oleh sel otak mati dengan cepat"],"answer":3,"explanation":"Jawapan yang tepat ialah D."},
      {"id":5,"section":"Petikan 4","track":"05 Track 5.mp3","question":"Apakah tindakan awal yang diperlukan bagi pesakit dimensia?","options":["Membawa pesakit berjumpa doktor","Membantu menguruskan kehidupan pesakit","Memastikan kehidupan mereka lebih efektif","Mendapatkan maklumat tentang sel-sel otak pesakit"],"answer":0,"explanation":"Jawapan yang tepat ialah A."},
      {"id":6,"section":"Petikan 5","track":"06 Track 6.mp3","question":"Apakah perkara yang diinginkan oleh Salma?","options":["Sarapan yang lebih enak.","Ibunya meluangkan masa bersamanya.","Kawan-kawan yang memahami dirinya.","Kehidupan yang senang seperti kawan-kawannya."],"answer":1,"explanation":"Jawapan yang tepat ialah B."},
      {"id":7,"section":"Petikan 5","track":"06 Track 6.mp3","question":"Apakah yang membezakan Salma dengan kawan-kawannya?","options":["Mereka menuntut di sekolah yang berbeza.","Mereka tinggal di kawasan perumahan yang jauh.","Kemewahan hidup yang sangat ketara di antara mereka.","Mereka mempunyai ayah sedangkan ayah Salma tidak bersamanya."],"answer":3,"explanation":"Jawapan yang tepat ialah D."},
      {"id":8,"section":"Petikan 6","track":"07 Track 7.mp3","question":"Pilih pernyataan yang betul.","options":["Zakiah pernah ikuti bengkel berpantun.","Aiman ialah sukarelawan di Kelab Masyarakat Kemboja.","Aiman dan Zakiah berminat untuk menganjurkan acara budaya.","Aiman dan Zakiah telah mendaftarkan diri untuk acara-acara budaya."],"answer":0,"explanation":"Jawapan yang tepat ialah A."},
      {"id":9,"section":"Petikan 6","track":"07 Track 7.mp3","question":"Apakah acara budaya yang sesuai untuk kanak-kanak?","options":["Tarian ronggeng","Acara berbalas pantun","Tarian dondang sayang","Acara Si Cilik Bercerita"],"answer":3,"explanation":"Jawapan yang tepat ialah D."},
      {"id":10,"section":"Petikan 6","track":"07 Track 7.mp3","question":"Apakah yang Zakiah dan Aiman perlu lakukan sebelum bertemu lagi?","options":["Mendapatkan kebenaran ibu bapa mereka","Mendaftarkan diri di Kelab Masyarakat Kemboja","Memilih acara mana yang mereka ingin turut serta","Menghubungi pihak penganjur untuk menjadi sukarelawan"],"answer":0,"explanation":"Jawapan yang tepat ialah A."}
    ]
  },
  latihan2: {
    title: "Latihan 2",
    subtitle: "10 soalan • 6 petikan",
    audioFolder: "audio2",
    questions: [
      {"id":1,"section":"Petikan 1","track":"02 Track 2.mp3","question":"Mengapakah ramai yang menggemari menonton televisyen?","options":["kerana banyak rancangan yang disiarkan","kerana ia mempunyai peranan terhadap masyarakat","kerana ada banyak berita yang menarik dilaporkan di televisyen","kerana mereka boleh mengikuti perkembangan semasa yang sedang berlaku"],"answer":0,"explanation":"Jawapan yang tepat ialah A."},
      {"id":2,"section":"Petikan 2","track":"03 Track 3.mp3","question":"Apakah berita yang disampaikan oleh Adi?","options":["Sharifah terkena jangkitan Covid-19.","Sharifah mengadu mengalami demam.","Muka Sharifah kelihatan pucat ketika di kelas.","Sharifah dikenakan perintah berkurung di rumah."],"answer":3,"explanation":"Jawapan yang tepat ialah D."},
      {"id":3,"section":"Petikan 2","track":"03 Track 3.mp3","question":"Mengapakah jawapan Mei Ling menenangkan hati Adi?","options":["Sharifah tidak suka melepak di luar.","Sharifah rajin menjaga kebersihan diri.","Mei Ling tidak fikir bahawa Sharifah ada masalah serius.","Sememangnya doktor akan memberikan cuti sakit 5 hari bagi demam flu biasa."],"answer":2,"explanation":"Jawapan yang tepat ialah C."},
      {"id":4,"section":"Petikan 3","track":"04 Track 4.mp3","question":"Mengapakah ramai penduduk Asia Tenggara menggunakan kunyit?","options":["Ia boleh dijadikan sebagai ubat tradisional.","Ia digunakan sebagai bahan masakan makanan mereka.","Ia mudah ditanam di wilayah India dan di negara-negara Asia.","Ia mudah didapatkan di pasar atau pasaraya dan murah harganya."],"answer":0,"explanation":"Jawapan yang tepat ialah A."},
      {"id":5,"section":"Petikan 4","track":"05 Track 5.mp3","question":"Pilih pernyataan yang TIDAK TEPAT tentang rumah panggung.","options":["Rumah panggung mempunyai tangga dan kolong rumah.","Rumah panggung mempunyai keunikan dan seni bina tersendiri.","Semua rumah di kepulauan Melayu memiliki jenis rumah panggung.","Pembinaan rumah panggung berkait rapat dengan kepercayaan, adat resam dan budaya orang Melayu."],"answer":2,"explanation":"Jawapan yang tepat ialah C."},
      {"id":6,"section":"Petikan 5","track":"06 Track 6.mp3","question":"Apakah tujuan diadakan acara di Kelab Masyarakat Sri Cempaka?","options":["menjual makanan dan permainan kanak-kanak.","menyambut perayaan ulang tahun kelab itu yang ke lima belas.","menyambut kedatangan tetamu terhormat iaitu seorang ahli parlimen.","mengadakan pertandingan tarian bagi kawasan undi Taman Cempaka."],"answer":1,"explanation":"Jawapan yang tepat ialah B."},
      {"id":7,"section":"Petikan 5","track":"06 Track 6.mp3","question":"Siapakah layak menerima belon secara percuma?","options":["kanak-kanak","ahli parlimen","penari-penari","pemain kompang"],"answer":0,"explanation":"Jawapan yang tepat ialah A."},
      {"id":8,"section":"Petikan 6","track":"07 Track 7.mp3","question":"Siapakah Salman dalam petikan tersebut?","options":["Anak murid Cikgu Zairi.","Bekas pelajar Cikgu Zairi.","Seorang usahawan yang berjaya.","Seorang peniaga di estet perumahan Cikgu Zairi."],"answer":1,"explanation":"Jawapan yang tepat ialah B."},
      {"id":9,"section":"Petikan 6","track":"07 Track 7.mp3","question":"Apakah sebab Salman tidak mahu belajar lagi?","options":["Dia sudah patah semangat untuk belajar.","Dia meminati bidang perniagaan kecil-kecilan.","Dia bercita-cita untuk membuka restorannya sendiri.","Dia ingin membuktikan bahawa tanpa ijazah dia boleh berjaya."],"answer":0,"explanation":"Jawapan yang tepat ialah A."},
      {"id":10,"section":"Petikan 6","track":"07 Track 7.mp3","question":"Pada pendapat kamu, adakah Salman akan berjaya?","options":["Ya, sebab dia berani belajar daripada bangsa lain.","Ya, sebab Cikgu Zairi menaruh keyakinan kepadanya.","Ya, sebab dia memiliki wawasan dan pendirian sendiri.","Ya, sebab dia sudah berniaga sejak meninggalkan bangku sekolah."],"answer":2,"explanation":"Jawapan yang tepat ialah C."}
    ]
  }
};
